server:
  port: 8090
spring:
  profiles:
    active: dev
    include: secret
  jackson:
    serialization:
      fail-on-empty-beans: false
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false
logging:
  level:
    org.example.springbootrabbitmq: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:${server.port}"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: www.test.com
    frontUrl: "https://${custom.prod.cookieDomain}"
    backUrl: "https://${custom.prod.cookieDomain}"
    database:
      password: NEED_TO_SECRET
    members:
      system:
        password: NEED_TO_SECRET
      admin:
        password: NEED_TO_SECRET
      garage:
        password: NEED_TO_SECRET
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: sb-2024-04-14
  jwt:
    secretKey: ON_SECRET
  accessToken:
    expirationSec: '#{60*60}'
  temp:
    dirPath: c:/temp/sb_2024_04_14_dev/temp
  genFile:
    dirPath: c:/temp/sb_2024_04_14_dev